### ISSUE TITLE
Token missing after initial redirect

### ISSUE THREAD

**Issue by fero1xd** [openauthjs/openauth#15]
It seems that after being redirected from /callback to /, the access and refresh tokens are not present in the request. However, after the initial redirect, every subsequent request appears to include the tokens. I'm not very familiar with Astro, so this might be something specific to the framework. Here are some screenshots.

![1](https://github.com/user-attachments/assets/61fd9f76-f4ea-4ab2-ba18-2289c066b0ab)
![2](https://github.com/user-attachments/assets/d43e26ed-71f9-4f10-b42d-0b4f5dd34e04)
![3](https://github.com/user-attachments/assets/8dff14d9-c628-4c07-8188-ab1f0f12cc91)

This results in user getting redirected back to the authorize page.

**Comment by adpadillar** [comment]
i got a similar problem and i fixed it by using `sameSite: "lax"` while setting the cookies. this is my nextjs example

```ts
export async function setTokens(access: string, refresh: string) {
  const c = await cookies();

  c.set("access_token", access, {
    httpOnly: true,
    sameSite: "lax", // strict breaks?
    path: "/",
    maxAge: 34560000,
  });

  c.set("refresh_token", refresh, {
    httpOnly: true,
    sameSite: "lax",
    path: "/",
    maxAge: 34560000,
  });
}
```

related: https://github.com/vercel/next.js/discussions/17612

**Comment by ripley** [comment]
> 
> might be good to open a pr to update the astro example if people get confused by this? that's how i ended up with the same problem
> 
> related: [vercel/next.js#17612](https://github.com/vercel/next.js/discussions/17612)

Yeah not only astro, I ran into the same issue with the Lambda example.
