### ISSUE TITLE
Missing CSRF with the `state` search param

### ISSUE THREAD

**Issue by sergiodxa** [openauthjs/openauth#17]
Right now when using `client.authorize` or `client.pkce` you don't get a `state` parameter in the URL, from the spec CSRF is a must and should use a state search param.

> The client MUST implement CSRF protection for its redirection URI.
>   This is typically accomplished by requiring any request sent to the
>   redirection URI endpoint to include a value that binds the request to
>   the user-agent's authenticated state (e.g., a hash of the session
>   cookie used to authenticate the user-agent).  The client SHOULD
>   utilize the "state" request parameter to deliver this value to the
>   authorization server when making an authorization request.

It could be easily added after the OpenAuth clients generate it but the issuer needs to include it again on the redirect to the callback, and since it needs to be a non-guessable it would be better if OpenAuth client generate it randomly so people don't use it to keep things like a returnTo value.

**Comment by thdxr** [comment]
good call having the client do this automatically makes sense. only thing is the caller needs to make sure they store it.

i thought we were including it on the redirect but i'll doublecheck

**Comment by sergiodxa** [comment]
If I'm correct, this https://github.com/openauthjs/openauth/blob/a5858756a4c1a172567ab62be29d80f8d4806035/packages/openauth/src/authorizer.ts#L156 means the authorizer is sending back the state, so the only missing part would be to have the client generate it for you.

I think `client.pkce` API returning `[verifier, redirect]` is a good pattern.

```ts
let [state, redirect] = client.authorize(clientId, redirectUri, "code")
let [state, verifier, redirect] = await client.pkce(clientId, redirectUri)
```

**Comment by thdxr** [comment]
the `authorize` function will generate a state parameter automatically now
