### ISSUE TITLE
createClient tree-shaking

### ISSUE THREAD

**Issue by r2d4** [openauthjs/openauth#22]
`import { createClient } from "@openauthjs/openauth";` 

fails on the client (nextjs) because it has a transitive dependency `node:crypto` via `hono` via the root import. Next does not polyfill `node:crypto` on purpose (?).

```
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:crypto
./node_modules/.pnpm/hono@4.6.13/node_modules/hono/dist/adapter/aws-lambda/handler.js
./node_modules/.pnpm/hono@4.6.13/node_modules/hono/dist/adapter/aws-lambda/index.js
./node_modules/.pnpm/@openauthjs+openauth@0.0.20_arctic@2.3.0_hono@4.6.13/node_modules/@openauthjs/openauth/dist/esm/authorizer.js
./node_modules/.pnpm/@openauthjs+openauth@0.0.20_arctic@2.3.0_hono@4.6.13/node_modules/@openauthjs/openauth/dist/esm/index.js
```
Instead, this works -- 

`import { createClient } from "@openauthjs/openauth/client";`.

Not a critical issue, but maybe a UX one getting started.

**Comment by thdxr** [comment]
yeah i probably am going to get rid of that root export since some bundlers have a hard time with it

client might move to its own package at some point

**Comment by thdxr** [comment]
removed from all our examples, left it in there for now but will remove for 1.0
