### ISSUE TITLE
Don't recommend localStorage (or sessionStorage) for holding auth credentials (security risk)

### ISSUE THREAD

**Issue by ghchaosfae** [openauthjs/openauth#23]
Websites/app should *never* store credentials (or anything else sensitive) in localStorage or sessionStorage (web storage) as suggested by the example here: https://github.com/openauthjs/openauth?tab=readme-ov-file#spa-sites-mobile-apps-etc

A reference: https://www.rdegges.com/2018/please-stop-using-local-storage/

If a use case can not be accomplished without putting credentials in web storage, then that use case is *incompatible* with user security and any documentation touching on the subject should *strongly* discourage attempting it.

**Comment by thdxr** [comment]
the recommendation i feel comfortable with is storing refresh token in some kind of browser storage and keeping access token in memory

the reality is people build client only applications - telling them they should not do this is not within scope of this project

as mentioned in my other reply i am not interested in responding to extreme positions on security that state "x is bad"

**Comment by danielweck** [comment]
For the benefit of future readers who like to explore closed issues, here is some additional reading :)

https://github.com/pilcrowonpaper/copenhagen/blob/main/pages%2Fsessions.md

https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets%2FSession_Management_Cheat_Sheet.md
