### ISSUE TITLE
/token endpoint CORS issue

### ISSUE THREAD

**Issue by beeirl** [openauthjs/openauth#48]
Still getting CORS errors with PKCE flow after calling `client.exchange`.

```
Access to fetch at 'https://<redacted>.lambda-url.us-east-1.on.aws/token' from origin 'http://localhost:5173' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
@thdxr think this could be caused by the sst component because I think the underlying router sets wildcard cors headers as well?

**Comment by strackfeldt** [comment]
I did cors myself, this worked for me:

```typescript
let app = new Hono();
app.use(cors());
app.mount("/", auth.fetch);
```

**Comment by beeirl** [comment]
@strackfeldt but cors config is already in place https://github.com/openauthjs/openauth/blob/master/packages/openauth/src/authorizer.ts#L355

**Comment by thdxr** [comment]
ah i did not test through the lambda function - let me see that

**Comment by thdxr** [comment]
i made an update to the Auth component to not set cors automatically (was being done by lambda function url) - but i have not tested it yet

**Comment by beeirl** [comment]
Saw that. I've upgraded my sst and seems to be working for me. Thanks.

**Comment by beeirl** [comment]
I still keep running into weird cors issues:

> Access to fetch at '<redacted>.lambda-url.us-east-1.on.aws/token' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Steps to reproduce:
1. run `sst dev`
2. authorize the user
3. call `client.refresh(refresh, { access })` -> no cors error
4. (keep the browser tab open)
5. restart `sst dev`
6. call `client.refresh(refresh, { access })` again -> cors error

I was sometimes able to reproduce this by making changes to my code while `sst dev` was running but not as reliably as the steps above.

**Comment by beeirl** [comment]
Created a minimal example to reproduce this issue reliably by following the steps mentioned in my previous comment:
```ts
// infra/api.ts
export const api = new sst.aws.Function('Api', {
  handler: './packages/functions/src/api.handler',
  url: {
    cors: false,
  },
})
```
```ts
// infra/web.ts
import { api } from './api'

export const webapp = new sst.aws.StaticSite('Web', {
  path: './packages/web',
  build: {
    output: 'dist',
    command: 'bun run build',
  },
  environment: {
    VITE_API_URL: api.url,
  },
})
```
```ts
// packages/functions/src/api.ts
import { Hono } from 'hono'
import { handle } from 'hono/aws-lambda'
import { cors } from 'hono/cors'

export const app = new Hono().post(
  '/',
  cors({
    origin: '*',
    allowHeaders: ['*'],
    allowMethods: ['POST'],
    credentials: false,
  }),
  async (c) => {
    return c.json({ result: 'ok' }, 200)
  }
)

export const handler = handle(app)
```
```tsx
// packages/web/src/main.tsx
await fetch(import.meta.env.VITE_API_URL, {
  method: 'POST',
})
```

**Comment by thdxr** [comment]
this should be fixed in latest sst - leave a commennt if not

**Comment by sam-goodwin** [comment]
I think there may still be a bug here somewhere, perhaps in `sst dev` proxy server?

I have to workaround it like this for now:
```ts
export const handler = async (event: any, context: any) => {
  const response = await _handler(event, context);
  delete response.headers["access-control-allow-origin"];
  return response;
};
```

**Comment by flatplate** [comment]
I had the same issue. My issue was that I was using `sst.aws.Function` for my auth server, instead of `sst.aws.Auth`.

`sst.aws.Function` also works but you need to pass in `url: { cors: false }`
