### ISSUE TITLE
Support First and Last name fields

### ISSUE THREAD

**Issue by usama-m98** [openauthjs/openauth#57]
I'd like to have the ability to add First and Last name fields in the password ui register flow.

**Comment by beeirl** [comment]
You need to build a custom ui for this or extend the existing UI components

**Comment by usama-m98** [comment]
It looks like I'll have to also extend the password adapter as well, since it doesn't accept a first and last name field.

**Comment by thdxr** [comment]
i'd recommend collecting these things after auth is done in your application layer

but it is technically possible since the callbacks have all the form data

**Comment by usama-m98** [comment]
I've chosen to do this afterwards like you recommended, I'll close this now.
