### ISSUE TITLE
Undefined provider in the success callback

### ISSUE THREAD

**Issue by jordanecure** [openauthjs/openauth#76]
### Issue

In the success callback the provider is undefined.

### Reproduction

sst 3.4.3

```
const app = authorizer({
  subjects,
  providers: {
    code: CodeAdapter<{ email: string }>(
      CodeUI({
        sendCode: async (claims, code) => {
          console.log('Code adapter sendCode:', code);
          return Promise.resolve();
        }
      })
    )
  },
  success: async (ctx, value) => {
    // Expect value.provider to be "code" but got undefined
    console.log('Success handler value:', value.provider);

    return ctx.subject('user', {
      email: 'some-email'
    });
  }
});

export const handler = handle(app);
```

Auth flow is triggered by accessing to:

https://auth.domain.com/authorize?redirect_uri=http://localhost:3000&response_type=token&client_id=local

` console.log('Success handler value:', value.provider);` will log un undefined value

**Comment by thdxr** [comment]
i just tried recreating this and i can't - you can see how we're using it at terminal https://github.com/terminaldotshop/terminal/blob/dev/packages/functions/src/auth2.ts#L111

and try it
https://auth.terminal.shop/authorize?redirect_uri=https://localhost&response_type=code&client_id=xxx

**Comment by jordanecure** [comment]
I found the cause. 

hono > 4.0.0 is required have the provider defined. 
With version 3.0.0 provider is undefined.
